Repository oracle/microservices-datadriven, pull requests merged in 2023-04, with the labels that each got.

#615 AISIX script updates
  cloudbank-v2/spring-apps/apisix-routes/create-accounts-route.sh
  cloudbank-v2/spring-apps/apisix-routes/create-creditscore-route.sh
  cloudbank-v2/spring-apps/apisix-routes/create-customer-route.sh
Labels: OCA Verified

#616 ORA-01400: cannot insert NULL fix
  cloudbank-v2/spring-apps/customer/src/main/java/com/example/customer/model/Customers.java
Labels: OCA Verified

#618 fix for issue#613
  workshops/oracleAQ/qJava/pom.xml
  workshops/oracleAQ/qJava/src/main/java/com/examples/config/ConstantName.java
  workshops/oracleAQ/qJava/src/main/java/com/examples/controller/OracleAQController.java
  workshops/oracleAQ/qJava/src/main/java/com/examples/enqueueDequeueTxEventQ/EnqueueDequeueTxEventQ.java
  workshops/oracleAQ/qJava/src/main/java/com/examples/util/pubSubUtil.java
  workshops/oracleAQ/qJava/src/main/java/com/examples/workflowTxEventQ/WorkflowTxEventQ.java
  workshops/oracleAQ/setup.sh
Labels: OCA Verified

#617 WIP: mvn package warning fix, removed server port from credit score application
  cloudbank-v2/spring-apps/account/pom.xml
  cloudbank-v2/spring-apps/creditscore/pom.xml
  cloudbank-v2/spring-apps/creditscore/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/customer/pom.xml
  cloudbank-v2/spring-apps/pom.xml
  cloudbank-v2/spring-apps/transfer/pom.xml
Labels: OCA Verified

#624 614 azure support updated on prem
  docs-source/mbaas/content/azure/AzureCloudShellIcon.png
  docs-source/mbaas/content/azure/AzureConfigure.png
  docs-source/mbaas/content/azure/AzureUpload.png
  docs-source/mbaas/content/azure/_index.md
  docs-source/mbaas/content/azure/userprofilemenu.png
  docs-source/mbaas/content/on-premises/_index.md
  docs-source/mbaas/data/menu/main.yaml
  docs-source/spring/content/azure/AzureCloudShellIcon.png
  docs-source/spring/content/azure/AzureConfigure.png
  docs-source/spring/content/azure/AzureUpload.png
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/azure/userprofilemenu.png
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#628 VSCode Plugin docs
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/platform/vscode-plugin/images/additional.jpg
  docs-source/spring/content/platform/vscode-plugin/images/admin.jpg
  docs-source/spring/content/platform/vscode-plugin/images/apisisx.jpg
  docs-source/spring/content/platform/vscode-plugin/images/appName.jpg
  docs-source/spring/content/platform/vscode-plugin/images/application.jpg
  docs-source/spring/content/platform/vscode-plugin/images/applications.jpg
  docs-source/spring/content/platform/vscode-plugin/images/bindigDBpwd.jpg
  docs-source/spring/content/platform/vscode-plugin/images/bindingTF.jpg
  docs-source/spring/content/platform/vscode-plugin/images/browse.jpg
  docs-source/spring/content/platform/vscode-plugin/images/choseContext.jpg
  docs-source/spring/content/platform/vscode-plugin/images/clusters.jpg
  docs-source/spring/content/platform/vscode-plugin/images/configurations.jpg
  docs-source/spring/content/platform/vscode-plugin/images/confirm.jpg
  docs-source/spring/content/platform/vscode-plugin/images/credentials.jpg
  docs-source/spring/content/platform/vscode-plugin/images/database.jpg
  docs-source/spring/content/platform/vscode-plugin/images/dbCredentials.jpg
  docs-source/spring/content/platform/vscode-plugin/images/detailsConf.jpg
  docs-source/spring/content/platform/vscode-plugin/images/extensions.jpg
  docs-source/spring/content/platform/vscode-plugin/images/getKubeConfig.jpg
  docs-source/spring/content/platform/vscode-plugin/images/grafana-browser.jpg
  docs-source/spring/content/platform/vscode-plugin/images/grafana.jpg
  docs-source/spring/content/platform/vscode-plugin/images/install.jpg
  docs-source/spring/content/platform/vscode-plugin/images/menubar.jpg
  docs-source/spring/content/platform/vscode-plugin/images/oktunnel.jpg
  docs-source/spring/content/platform/vscode-plugin/images/onenode.jpg
  docs-source/spring/content/platform/vscode-plugin/images/oractlCred.jpg
  docs-source/spring/content/platform/vscode-plugin/images/password.jpg
  docs-source/spring/content/platform/vscode-plugin/images/refreshApplications.jpg
  docs-source/spring/content/platform/vscode-plugin/images/reloadWindow.jpg
  docs-source/spring/content/platform/vscode-plugin/images/reloadWindowError.jpg
  docs-source/spring/content/platform/vscode-plugin/images/serviceName.jpg
  docs-source/spring/content/platform/vscode-plugin/images/tunnel.jpg
  docs-source/spring/content/platform/vscode-plugin/images/uploadJar.jpg
  docs-source/spring/data/menu/main.yaml
Labels: documentation, OCA Verified

#627 0.3.0 release notes and other doc updates
  docs-source/mbaas/content/release-notes/_index.md
  docs-source/spring/content/blogs/_index.md
  docs-source/spring/content/release-notes/_index.md
Labels: documentation, OCA Verified

#629 VSCode plugin update & on-prem doc fix
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
Labels: bug, documentation, OCA Verified

#620 Update CLI documentation.
  docs-source/spring/content/development/cli/_index.md
Labels: documentation, OCA Verified

#631 Mark/kick docs
  mbaas/azure/index.html
Labels: OCA Verified

#633 typos
  spring/platform/vscode-plugin/index.html
Labels: OCA Verified

#634 fix for the textfield bug
  txeventQUI/asset-manifest.json
  txeventQUI/index.html
  txeventQUI/static/js/787.5e3799a0.chunk.js
  txeventQUI/static/js/main.759cd495.js
  txeventQUI/static/js/main.fa30c353.js
Labels: OCA Verified

#635 add intro video to home page
  docs-source/spring/content/_index.md
Labels: OCA Verified

#639 publish doc udpates
  spring/blogs/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#642 Spring Boot Starter Wallet
  spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/LICENSE.txt
  spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/THIRD_PARTY_LICENSES.txt
  spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/oracle-spring-boot-starter-wallet-2.7.7.pom
  spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starter-wallet/pom.xml
  spring/oracle-spring-boot-starters/2.7.7/oracle-spring-boot-starters-2.7.7.pom
  spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/LICENSE.txt
  spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/THIRD_PARTY_LICENSES.txt
  spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/oracle-spring-boot-starter-wallet-3.0.2.pom
  spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starter-wallet/pom.xml
  spring/oracle-spring-boot-starters/3.0.2/oracle-spring-boot-starters-3.0.2.pom
Labels: enhancement, OCA Verified
