Repository oracle/microservices-datadriven, pull requests merged in 2023-01, with the labels that each got.

#526 Doc updates - post xmas review
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/sample-apps/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/setup/_index.md
  mbaas-developer-preview/walking-history/App.js
Labels: OCA Verified

#525 OBaaS::Docs - Add prereqs and change Setup menu
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/sample-apps/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/data/menu/main.yaml
  docs-source/spring/resources/_gen/images/setup/cluster-access/oci-cloud-shell_hu095942552e1dd58dc3ef4f1540dddf42_41551_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/cluster-access/oci-cloud-shell_hu095942552e1dd58dc3ef4f1540dddf42_41551_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/cluster-access/oci-cloud-shell_hu095942552e1dd58dc3ef4f1540dddf42_41551_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/setup/cluster-access/oci-cloud-shell_hu095942552e1dd58dc3ef4f1540dddf42_41551_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/cluster-access/oci-cloud-shell_hu095942552e1dd58dc3ef4f1540dddf42_41551_600x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal-details_hu0a81ffeafab24a7d12694cda6c1940c7_169532_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal-details_hu0a81ffeafab24a7d12694cda6c1940c7_169532_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal-details_hu0a81ffeafab24a7d12694cda6c1940c7_169532_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal-details_hu0a81ffeafab24a7d12694cda6c1940c7_169532_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal-details_hu0a81ffeafab24a7d12694cda6c1940c7_169532_600x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal_hu0a81ffeafab24a7d12694cda6c1940c7_213389_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal_hu0a81ffeafab24a7d12694cda6c1940c7_213389_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal_hu0a81ffeafab24a7d12694cda6c1940c7_213389_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal_hu0a81ffeafab24a7d12694cda6c1940c7_213389_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-cloud-portal_hu0a81ffeafab24a7d12694cda6c1940c7_213389_600x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-download-wallet_huc241caf1daae923ec5f0e3438f90e082_937579_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-download-wallet_huc241caf1daae923ec5f0e3438f90e082_937579_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-download-wallet_huc241caf1daae923ec5f0e3438f90e082_937579_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-download-wallet_huc241caf1daae923ec5f0e3438f90e082_937579_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-adb-download-wallet_huc241caf1daae923ec5f0e3438f90e082_937579_600x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-bastion-session-create_hu34b22c0de5a7de184b612596d2de8425_307323_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-bastion-session-create_hu34b22c0de5a7de184b612596d2de8425_307323_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-bastion-session-create_hu34b22c0de5a7de184b612596d2de8425_307323_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-bastion-session-create_hu34b22c0de5a7de184b612596d2de8425_307323_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/setup/database/oci-bastion-session-create_hu34b22c0de5a7de184b612596d2de8425_307323_600x0_resize_box_3.png
Labels: OCA Verified

#530 Download DB wallet issue is fixed
  workshops/microservices-data-refactoring/dra-graph-client/pom.xml
  workshops/microservices-data-refactoring/dra-graph-client/src/main/java/com/oracle/ms/app/Constants.java
  workshops/microservices-data-refactoring/dra-graph-client/src/main/java/com/oracle/ms/app/InfomapGraphClient.java
  workshops/microservices-data-refactoring/dra-graph-client/src/main/resources/db-config.properties
  workshops/microservices-data-refactoring/dra-graph-client/src/main/resources/graph-config.properties
Labels: OCA Required

#532 Spring Boot Starters for UCP and AQ JMS, and a sample app
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/pom.xml
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/src/main/java/com/example/aqjms/Email.java
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/src/main/java/com/example/aqjms/JmsSampleApplication.java
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/src/main/java/com/example/aqjms/Receiver.java
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/src/main/resources/application.properties
  mbaas-developer-preview/sample-spring-apps/pom.xml
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/pom.xml
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/src/main/java/com/oracle/spring/aqjms/AqJmsAutoConfiguration.java
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/src/main/java/com/oracle/spring/aqjms/AqJmsConfigurationProperties.java
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/src/main/resources/META-INF/spring.factories
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-ucp/pom.xml
  spring/oracle-spring-boot-starters/pom.xml
Labels: OCA Verified

#535 fix maven coords
  mbaas-developer-preview/sample-spring-apps/aqjms_sample/pom.xml
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/pom.xml
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-ucp/pom.xml
  spring/oracle-spring-boot-starters/pom.xml
Labels: OCA Verified

#536 renames
  docs-source/mbaas/config.toml
  docs-source/mbaas/content/_index.md
  docs-source/mbaas/content/cluster-access/_index.md
  docs-source/mbaas/content/dashboard/_index.md
  docs-source/mbaas/content/database/_index.md
  docs-source/mbaas/content/firebase-emulation/friendly-eats.md
  docs-source/mbaas/content/getting-started/dashboard.md
  docs-source/mbaas/content/getting-started/objects.md
  docs-source/mbaas/content/sample-apps/walking-history/_index.md
  docs-source/mbaas/content/setup/_index.md
  docs-source/mbaas/content/uninstall/_index.md
  docs-source/spring/config.toml
  docs-source/spring/content/_index.md
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/observability/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/config/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/sample-apps/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/uninstall/_index.md
  mbaas-developer-preview/parsef/README.md
  mbaas-developer-preview/sample-spring-apps/README.md
  mbaas-developer-preview/sample-spring-apps/pom.xml
  mbaas-developer-preview/walking-history/README.md
Labels: OCA Verified

#527 CLI doc mod for command rename (to "obaas") new command help menu, etc.
  docs-source/spring/content/development/cli/_index.md
Labels: OCA Required

#543 Updated the opg-client library and reading graph as pg-view type
  workshops/microservices-data-refactoring/dra-graph-client/src/main/java/com/oracle/ms/app/InfomapGraphClient.java
Labels: OCA Required

#539 Documentation updates
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/conductor/conductor_server_swagger.png
  docs-source/spring/content/platform/conductor/conductor_server_ui.png
  docs-source/spring/content/platform/conductor/conductor_ui_tasks.png
  docs-source/spring/content/platform/conductor/conductor_ui_workflows.png
  docs-source/spring/content/platform/eureka/_index.md
Labels: documentation, OCA Verified

#544 Infomap output of 974 nodes graph is attached.
  workshops/microservices-data-refactoring/livelabs/resources/dra-output-medical-records-974-nodes.txt
Labels: OCA Verified

#545 add TPL files
  spring/oracle-spring-boot-starters/THIRD_PARTY_LICENSES.txt
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-aqjms/THIRD_PARTY_LICENSES.txt
  spring/oracle-spring-boot-starters/oracle-spring-boot-starter-ucp/THIRD_PARTY_LICENSES.txt
Labels: OCA Verified

#546 WIP:Documentation bugs and Vault docs
  docs-source/spring/content/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/config/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vault/vault-login.png
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/uninstall/_index.md
  docs-source/spring/data/menu/main.yaml
  docs-source/spring/resources/_gen/images/platform/vault/vault-login_hub258ebe5f5f044ba2a1413f85fe5f105_99398_1200x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/platform/vault/vault-login_hub258ebe5f5f044ba2a1413f85fe5f105_99398_1800x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/platform/vault/vault-login_hub258ebe5f5f044ba2a1413f85fe5f105_99398_180x180_fill_box_center_3.png
  docs-source/spring/resources/_gen/images/platform/vault/vault-login_hub258ebe5f5f044ba2a1413f85fe5f105_99398_320x0_resize_box_3.png
  docs-source/spring/resources/_gen/images/platform/vault/vault-login_hub258ebe5f5f044ba2a1413f85fe5f105_99398_600x0_resize_box_3.png
Labels: documentation, OCA Verified

#549 Fixes for Issue #547 and deprecated TF attributes
  grabdish/terraform/containerengine.tf
  grabdish/terraform/database.tf
  infra/db/atp/terraform/database.tf
  infra/db/dbcs/terraform/database.tf
  infra/k8s/oke/terraform/containerengine.tf
Labels: OCA Verified

#550 Vault, overall doc changes, grabdish changes
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vault/vault-create-secret.png
  docs-source/spring/content/platform/vault/vault-home.png
  docs-source/spring/content/platform/vault/vault-kv-v2-home.png
  docs-source/spring/content/platform/vault/vault-secret.png
  docs-source/spring/content/platform/vault/vault-show-secret.png
  docs-source/spring/content/setup/_index.md
  grabdish/config/db/params.env
Labels: documentation, OCA Verified

#553 Setup documentation updates
  docs-source/spring/.gitignore
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/oci-private-template-create-stack-config-lb-vault.png
  docs-source/spring/content/setup/oci-private-template-create-stack-config-review.png
  docs-source/spring/content/setup/oci-private-template-create-stack-config.png
  docs-source/spring/content/setup/oci-private-template-create-stack-info.png
  docs-source/spring/content/setup/oci-stack-apply-logs.png
  docs-source/spring/content/setup/oci-stack-apply.png
  docs-source/spring/content/setup/oci-stack-output-oke.png
  docs-source/spring/content/setup/oci-stack-outputs.png
  docs-source/spring/content/setup/oci-stack-plan.png
  docs-source/spring/static/ebaas-mp-listing.png
Labels: OCA Verified
