Repository oracle/microservices-datadriven, pull requests merged in 2023-06, with the labels that each got.

#667 update blogs
  docs-source/spring/content/blogs/_index.md
  docs-source/spring/content/blogs/youtube.png
Labels: OCA Verified

#668 publish blog updates
  spring/blogs/index.html
  spring/blogs/youtube.png
  spring/search/en.data.min.json
Labels: OCA Verified

#669 Fixes CloudBank apps enabling observability
  cloudbank-v2/spring-apps/account/pom.xml
  cloudbank-v2/spring-apps/account/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/creditscore/pom.xml
  cloudbank-v2/spring-apps/customer/pom.xml
  cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/pom.xml
  cloudbank-v2/spring-apps/transfer/pom.xml
  cloudbank-v2/spring-apps/transfer/src/main/java/com/example/transfer/servlet/filter/SpringMvcPrefixEnforcerFilter.java
  cloudbank-v2/spring-apps/transfer/src/main/resources/application.yaml
Labels: OCA Verified

#664 Minor fixes to Azure Install
  docs-source/spring/content/azure/_index.md
Labels: documentation, OCA Verified

#670 add new blog from corrado
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#671 publish blog updates
  spring/azure/index.html
  spring/blogs/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#672 0.3.1 rel notes
  docs-source/spring/content/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/setup/_index.md
Labels: documentation, OCA Verified

#674 oops
  docs-source/spring/content/release-notes/_index.md
Labels: documentation, OCA Verified

#675 publish typo correction
  spring/release-notes/index.html
  spring/search/en.data.min.json
Labels: documentation, OCA Verified

#676 LB version change, account cleanup
  cloudbank-v2/spring-apps/account/pom.xml
  cloudbank-v2/spring-apps/customer/pom.xml
Labels: bug, OCA Verified

#678 publish azure vid updates
  spring/azure/index.html
  spring/blogs/index.html
  spring/search/en.data.min.json
  spring/setup/index.html
Labels: OCA Verified

#680 LB updates
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/controller.yaml
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/grants.sql
Labels: OCA Verified

#681 Cbv3 updates
  cloudbank-v3/spring-apps/FIX.md
  cloudbank-v3/spring-apps/README.md
  cloudbank-v3/spring-apps/account/pom.xml
  cloudbank-v3/spring-apps/account/src/main/resources/banner.txt
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/rest.sql
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/txeventq.sql
  cloudbank-v3/spring-apps/checks/src/main/resources/banner.txt
  cloudbank-v3/spring-apps/creditscore/src/main/resources/banner.txt
  cloudbank-v3/spring-apps/customer/src/main/resources/banner.txt
  cloudbank-v3/spring-apps/transfer/src/main/resources/banner.txt
Labels: enhancement, OCA Verified
