Repository oracle/microservices-datadriven, pull requests merged in 2023-11, with the labels that each got.

#776 Typo in README
  README.md
Labels: documentation, OCA Verified

#762 Oracle Backend for Spring Boot and Microservices - Docs
  docs-source/spring/content/development/cli/_index.md
Labels: documentation, OCA Verified

#775 Updated README and customer
  cloudbank-v3/spring-apps-spring3/README.md
  cloudbank-v3/spring-apps-spring3/customer/src/main/resources/application.yaml
Labels: bug, documentation, OCA Verified

#777 Remove of NIB build in pom.xml files
  cloudbank-v3/spring-apps-spring3/account/pom.xml
  cloudbank-v3/spring-apps-spring3/checks/pom.xml
  cloudbank-v3/spring-apps-spring3/creditscore/pom.xml
  cloudbank-v3/spring-apps-spring3/customer/pom.xml
  cloudbank-v3/spring-apps-spring3/testrunner/pom.xml
  cloudbank-v3/spring-apps-spring3/transfer/pom.xml
Labels: bug, OCA Verified

#778 Update to readme
  cloudbank-v3/spring-apps-spring3/README.md
Labels: documentation, OCA Verified

#779 Version update and typos
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/ebaas-mp-listing.png
Labels: documentation, OCA Verified

#781 Release Notes
  docs-source/spring/content/release-notes/_index.md
Labels: documentation, OCA Verified

#784 Update to Config Server docs
  docs-source/spring/content/platform/config/_index.md
Labels: documentation, OCA Verified

#785 Updated starters, with doc and CB3 updated to consume them
  cloudbank-v3/spring-apps-spring3/account/src/main/resources/application.yaml
  cloudbank-v3/spring-apps-spring3/checks/src/main/resources/application.yaml
  docs-source/spring/content/development/starters/_index.md
  docs-source/spring/content/starters/_index.md
  docs-source/spring/content/starters/aqjms.md
  docs-source/spring/content/starters/ucp.md
  docs-source/spring/content/starters/wallet.md
  docs-source/spring/data/menu/main.yaml
  docs-source/spring/data/menu/more.yaml
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-ucp/oracle-spring-boot-starter-ucp-23.4.0.pom
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-ucp/pom.xml
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-wallet/oracle-spring-boot-starter-wallet-23.4.0.pom
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-wallet/pom.xml
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starters-23.4.0.pom
Labels: OCA Verified

#786 changes required to publish to central
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-ucp/src/main/java/com/oracle/database/spring/Starter.java
  spring/oracle-spring-boot-starters/23.4.0/oracle-spring-boot-starter-wallet/src/main/java/com/oracle/database/spring/Starter.java
Labels: OCA Verified

#787 Add documentation of recommended settings and dependencies
  docs-source/spring/content/development/_index.md
  docs-source/spring/content/development/project.md
  docs-source/spring/content/development/setup.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#790 publish blog updates
  spring/blogs/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#791 fixed deploy command too long
  docs-source/spring/content/development/cli/_index.md
Labels: OCA Verified

#792 Added changeRole documentation
  docs-source/spring/content/security/azn-server/_index.md
Labels: documentation, OCA Verified
