Repository oracle/microservices-datadriven, pull requests merged in 2023-07, with the labels that each got.

#684 Atael/cbv3 updates
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/controller.yaml
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/grants.sql
  cloudbank-v3/spring-apps/account/src/main/resources/db/changelog/rest.sql
Labels: enhancement, OCA Verified

#696 Updated k8s version to 1.26.2 in container engine Terraform files
  grabdish/terraform/containerengine.tf
  infra/k8s/oke/terraform/containerengine.tf
Labels: OCA Verified

#697 Updated OCI provider in Terraform provider configuration
  grabdish/terraform/provider.tf
  infra/network/oci/terraform/provider.tf
Labels: OCA Verified

#700 publish corrado's update
  spring/blogs/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#703 Doc updates
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
Labels: OCA Verified

#704 Documentation updates 0.7.0
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/ebaas-mp-listing.png
  docs-source/spring/content/setup/oci-private-template-create-stack-config-lb-vault.png
  docs-source/spring/content/setup/oci-private-template-create-stack-config.png
  docs-source/spring/content/setup/oci-stack-app-name.png
  docs-source/spring/content/setup/oci-stack-db-options.png
  docs-source/spring/content/setup/oci-stack-parse-options.png
  docs-source/spring/static/ebaas-mp-listing.png
Labels: documentation, OCA Verified

#705 Publish docs for 0.7.0 release
  spring/index.html
  spring/on-premises/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/release-notes/index.xml
  spring/search/en.data.min.json
  spring/setup/ebaas-mp-listing.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_1200x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_1800x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_180x180_fill_box_center_3.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_320x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_600x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu796e5d7bb9b5db779966a1588bc45a30_463560_90x0_resize_box_3.png
  spring/setup/index.html
  spring/setup/oci-private-template-create-stack-config-lb-vault.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_1200x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_1800x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_180x180_fill_box_center_3.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_320x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_600x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config-lb-vault_hu248079d541f968b3f975baf4b37933d2_136465_90x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_1200x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_1800x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_180x180_fill_box_center_3.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_320x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_600x0_resize_box_3.png
  spring/setup/oci-private-template-create-stack-config_hue640d07687e4e06a95ecfd26bcf81c1d_85802_90x0_resize_box_3.png
  spring/setup/oci-stack-app-name.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_1200x0_resize_box_3.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_1800x0_resize_box_3.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_180x180_fill_box_center_3.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_320x0_resize_box_3.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_600x0_resize_box_3.png
  spring/setup/oci-stack-app-name_hu8c0a7565ca030d096aae1a11a896fbfc_59542_90x0_resize_box_3.png
  spring/setup/oci-stack-db-options.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_1200x0_resize_box_3.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_1800x0_resize_box_3.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_180x180_fill_box_center_3.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_320x0_resize_box_3.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_600x0_resize_box_3.png
  spring/setup/oci-stack-db-options_hub5b7dc8b386f792eccbd8605bd4aa7a6_111743_90x0_resize_box_3.png
  spring/setup/oci-stack-parse-options.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_1200x0_resize_box_3.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_1800x0_resize_box_3.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_180x180_fill_box_center_3.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_320x0_resize_box_3.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_600x0_resize_box_3.png
  spring/setup/oci-stack-parse-options_hub3f66028b935ef79250823e5a33a4f5e_90765_90x0_resize_box_3.png
  spring/sitemap.xml
Labels: OCA Verified

#706 Minor fixes to documentation
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/blogs/_index.md
  docs-source/spring/content/observability/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/ebaas-mp-listing.png
  docs-source/spring/content/setup/ebaas-stack-page1.png
  docs-source/spring/static/ebaas-stack-page1.png
Labels: OCA Verified

#710 Update link to azure package
  docs-source/mbaas/content/azure/_index.md
  docs-source/spring/content/azure/_index.md
Labels: OCA Verified

#711 add corrado's new blog to blog agg page
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#712 Incorporated several edits.
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
Labels: OCA Verified

#713 Incorporated many edits.
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/observability/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/uninstall/_index.md
Labels: OCA Verified

#682 Updated "Oracle Autonomous Database Shared" to the new name "Oracle A…
  docs-source/spring/content/_index.md
  docs-source/spring/content/getting-started/_index.md
Labels: documentation, OCA Verified

#694 Incorporated several editorial comments.
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/setup/_index.md
Labels: documentation, OCA Verified

#695 Incorporated several editorial comments.
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
Labels: documentation, OCA Verified

#714 fix error on blog page
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#715 publish doc updates
  spring/404.html
  spring/azure/index.html
  spring/blogs/index.html
  spring/cluster-access/index.html
  spring/database/index.html
  spring/development/cli/index.html
  spring/development/index.html
  spring/getting-started/index.html
  spring/index.html
  spring/observability/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/on-premises/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/platform/apigw/index.html
  spring/platform/conductor/index.html
  spring/platform/config/index.html
  spring/platform/eureka/index.html
  spring/platform/index.html
  spring/platform/spring-admin/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/sample-apps/index.html
  spring/search/en.data.min.json
  spring/security/index.html
  spring/setup/ebaas-mp-listing.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_1200x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_1800x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_180x180_fill_box_center_3.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_320x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_600x0_resize_box_3.png
  spring/setup/ebaas-mp-listing_hu3883450d77868f161022ea15467ac687_462104_90x0_resize_box_3.png
  spring/setup/ebaas-stack-page1.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_1200x0_resize_box_3.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_1800x0_resize_box_3.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_180x180_fill_box_center_3.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_320x0_resize_box_3.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_600x0_resize_box_3.png
  spring/setup/ebaas-stack-page1_hu3f0c778447f89c5f0324019bea7e326c_172785_90x0_resize_box_3.png
  spring/setup/index.html
  spring/sitemap.xml
  spring/tags/index.html
  spring/uninstall/index.html
Labels: OCA Verified

#716 Cloudbank V3 updates
  cloudbank-v3/spring-apps/account/src/main/resources/application.yaml
  cloudbank-v3/spring-apps/checks/src/main/resources/application.yaml
  cloudbank-v3/spring-apps/creditscore/src/main/resources/application.yaml
  cloudbank-v3/spring-apps/customer/src/main/resources/application.yaml
  cloudbank-v3/spring-apps/pom.xml
  cloudbank-v3/spring-apps/testrunner/src/main/resources/application.yaml
  cloudbank-v3/spring-apps/transfer/src/main/resources/application.yaml
Labels: bug, OCA Verified

#718 Update EBaaS OL8
  docs-source/mbaas/content/on-premises/ol8/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
Labels: OCA Verified

#720 Incorporated several edits.
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/config/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/uninstall/_index.md
Labels: documentation, OCA Verified

#721 publish doc updates from rhonda
  spring/cluster-access/index.html
  spring/database/index.html
  spring/development/cli/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/platform/conductor/index.html
  spring/platform/config/index.html
  spring/platform/eureka/index.html
  spring/platform/spring-admin/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/platform/vscode-plugin/index.xml
  spring/release-notes/index.html
  spring/search/en.data.min.json
  spring/setup/index.html
  spring/uninstall/index.html
Labels: OCA Verified

#717 Incorporated several edits.
  docs-source/spring/content/_index.md
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/setup/_index.md
Labels: documentation, OCA Verified

#722 Incorporated many edits (rhonda_072923_1)
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/uninstall/_index.md
Labels: documentation, OCA Verified

#723 Incorporated many edits (rhonda_072923_2).
  docs-source/mbaas/content/_index.md
  docs-source/mbaas/content/azure/_index.md
  docs-source/mbaas/content/getting-started/_index.md
  docs-source/mbaas/content/getting-started/objects.md
  docs-source/mbaas/content/on-premises/_index.md
  docs-source/mbaas/content/on-premises/macos_ventura/_index.md
  docs-source/mbaas/content/on-premises/ol8/_index.md
  docs-source/mbaas/content/setup/_index.md
Labels: documentation, OCA Verified

#724 Incorporated many edits (rhonda_073023_1).
  docs-source/mbaas/content/cluster-access/_index.md
  docs-source/mbaas/content/dashboard/_index.md
  docs-source/mbaas/content/database/_index.md
  docs-source/mbaas/content/firebase-emulation/_index.md
  docs-source/mbaas/content/firebase-emulation/extra.md
  docs-source/mbaas/content/firebase-emulation/friendly-eats.md
  docs-source/mbaas/content/firebase-emulation/scope.md
  docs-source/mbaas/content/getting-started/identity.md
  docs-source/mbaas/content/release-notes/_index.md
  docs-source/mbaas/content/sample-apps/_index.md
  docs-source/mbaas/content/sample-apps/walking-history/_index.md
  docs-source/mbaas/content/uninstall/_index.md
Labels: OCA Verified

#725 publish rhonda's updates
  mbaas/azure/index.html
  mbaas/azure/index.xml
  mbaas/cluster-access/index.html
  mbaas/dashboard/index.html
  mbaas/database/index.html
  mbaas/firebase-emulation/extra/index.html
  mbaas/firebase-emulation/friendly-eats/index.html
  mbaas/firebase-emulation/index.html
  mbaas/firebase-emulation/index.xml
  mbaas/firebase-emulation/scope/index.html
  mbaas/getting-started/identity/index.html
  mbaas/getting-started/index.html
  mbaas/getting-started/index.xml
  mbaas/getting-started/objects/index.html
  mbaas/index.html
  mbaas/index.xml
  mbaas/on-premises/index.html
  mbaas/on-premises/index.xml
  mbaas/on-premises/macos_ventura/index.html
  mbaas/on-premises/macos_ventura/index.xml
  mbaas/on-premises/ol8/index.html
  mbaas/on-premises/ol8/index.xml
  mbaas/release-notes/index.html
  mbaas/sample-apps/index.html
  mbaas/sample-apps/index.xml
  mbaas/sample-apps/walking-history/index.html
  mbaas/search/en.data.min.json
  mbaas/setup/index.html
  mbaas/sitemap.xml
  mbaas/uninstall/index.html
  spring/azure/index.html
  spring/azure/index.xml
  spring/cluster-access/index.html
  spring/database/index.html
  spring/development/cli/index.html
  spring/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/on-premises/index.html
  spring/on-premises/index.xml
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/on-premises/ol8/index.xml
  spring/platform/apigw/index.html
  spring/platform/index.html
  spring/platform/spring-admin/index.html
  spring/platform/spring-admin/index.xml
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/search/en.data.min.json
  spring/security/index.html
  spring/setup/index.html
  spring/sitemap.xml
  spring/uninstall/index.html
Labels: OCA Verified
