Repository oracle/microservices-datadriven, pull requests merged in 2023-08, with the labels that each got.

#729 fix some doc regressions
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#730 publish doc fixes
  spring/azure/index.html
  spring/blogs/index.html
  spring/cluster-access/index.html
  spring/database/index.html
  spring/development/cli/index.html
  spring/development/index.html
  spring/getting-started/index.html
  spring/index.html
  spring/observability/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/on-premises/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/platform/apigw/index.html
  spring/platform/conductor/index.html
  spring/platform/config/index.html
  spring/platform/eureka/index.html
  spring/platform/index.html
  spring/platform/spring-admin/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/sample-apps/index.html
  spring/search/en.data.min.json
  spring/security/index.html
  spring/setup/index.html
  spring/tags/index.html
  spring/uninstall/index.html
Labels: OCA Verified

#726 Incorporated several edits (rhonda_080123_1).
  docs-source/mbaas/content/_index.md
  docs-source/mbaas/content/azure/_index.md
  docs-source/mbaas/content/cluster-access/_index.md
  docs-source/mbaas/content/dashboard/_index.md
  docs-source/mbaas/content/database/_index.md
  docs-source/mbaas/content/firebase-emulation/_index.md
  docs-source/mbaas/content/firebase-emulation/extra.md
  docs-source/mbaas/content/firebase-emulation/friendly-eats.md
  docs-source/mbaas/content/firebase-emulation/scope.md
  docs-source/mbaas/content/getting-started/_index.md
  docs-source/mbaas/content/getting-started/dashboard.md
  docs-source/mbaas/content/getting-started/identity.md
  docs-source/mbaas/content/getting-started/objects.md
  docs-source/mbaas/content/on-premises/_index.md
  docs-source/mbaas/content/on-premises/macos_ventura/_index.md
  docs-source/mbaas/content/on-premises/ol8/_index.md
  docs-source/mbaas/content/release-notes/_index.md
  docs-source/mbaas/content/sample-apps/_index.md
  docs-source/mbaas/content/sample-apps/walking-history/_index.md
  docs-source/mbaas/content/setup/_index.md
  docs-source/mbaas/content/uninstall/_index.md
Labels: documentation, OCA Verified

#728 Incorporated several review edits (rhonda_080223_1)
  docs-source/mbaas/content/setup/_index.md
  docs-source/spring/content/_index.md
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/cluster-access/_index.md
  docs-source/spring/content/database/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/getting-started/_index.md
  docs-source/spring/content/observability/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/config/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/sample-apps/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/uninstall/_index.md
Labels: OCA Verified

#707 Terraform provider revert
  infra/network/oci/terraform/provider.tf
Labels: OCA Verified

#732 update/fix for certs without OU
  grabdish/inventory-dotnet/inventory-dotnet.csproj
Labels: OCA Verified

#733 Enable Jaeger tracing for Cloudbank
  cloudbank-v2/spring-apps/account/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/creditscore/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/pom.xml
  cloudbank-v2/spring-apps/transfer/src/main/resources/application.yaml
Labels: enhancement, OCA Verified

#735 Jaeger fixes for Cloudbank v2 and Spring 3
  cloudbank-v2/spring-apps-spring3/account/pom.xml
  cloudbank-v2/spring-apps-spring3/account/src/main/resources/application.yaml
  cloudbank-v2/spring-apps-spring3/creditscore/src/main/resources/application.yaml
  cloudbank-v2/spring-apps-spring3/customer/src/main/resources/application.yaml
  cloudbank-v2/spring-apps-spring3/pom.xml
  cloudbank-v2/spring-apps-spring3/transfer/src/main/resources/application.yaml
Labels: bug
