Repository oracle/microservices-datadriven, pull requests merged in 2023-05, with the labels that each got.

#643 Doc fixes
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
Labels: bug, documentation, OCA Verified

#645 Publish Andy's doc updates
  spring/development/cli/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#646 update blogs page
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#647 publish blog updates
  spring/blogs/index.html
  spring/search/en.data.min.json
Labels: OCA Verified

#651 Fixed broken link.
  docs-source/spring/content/on-premises/_index.md
Labels: OCA Required

#655 add yt link to blogs page in doc
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#658 Update docs
  LICENSE.txt
  README.md
  SECURITY.md
Labels: OCA Verified

#659 blog update
  docs-source/spring/content/blogs/_index.md
Labels: blog, OCA Verified

#660 Doc updates
  .gitignore
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/getting-started/_index.md
  docs-source/spring/content/sample-apps/_index.md
  docs-source/spring/content/sample-apps/obaas-sample-apps-build-result.png
  docs-source/spring/content/sample-apps/obaas-sample-apps-deploy.png
  docs-source/spring/content/sample-apps/oci-container-repository-create.png
  docs-source/spring/data/menu/main.yaml
Labels: documentation, OCA Verified

#661 Grafana fixes, version upgrades, spring starters
  cloudbank-v2/spring-apps/account/pom.xml
  cloudbank-v2/spring-apps/account/src/main/java/com/example/accounts/controller/AccountController.java
  cloudbank-v2/spring-apps/account/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/creditscore/pom.xml
  cloudbank-v2/spring-apps/creditscore/src/main/java/com/example/creditscore/controller/CreditScoreController.java
  cloudbank-v2/spring-apps/creditscore/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/customer/pom.xml
  cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/transfer/pom.xml
  cloudbank-v2/spring-apps/transfer/src/main/java/com/example/transfer/TransferService.java
  cloudbank-v2/spring-apps/transfer/src/main/resources/application.yaml
Labels: bug, enhancement, OCA Verified

#662 Spring starter update and typo
  cloudbank-v2/spring-apps/customer/pom.xml
  cloudbank-v2/spring-apps/customer/src/main/resources/application.yaml
  cloudbank-v2/spring-apps/transfer/src/main/java/com/example/transfer/TransferService.java
Labels: enhancement, blog, OCA Verified

#665 add john's blog page
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified
