Repository oracle/microservices-datadriven, pull requests merged in 2024-10, with the labels that each got.

#973 Cloudbank v4 updates
  cloudbank-v4/README.md
  cloudbank-v4/chatbot/checkstyle/checkstyle.xml
  cloudbank-v4/chatbot/checkstyle/suppressions.xml
  cloudbank-v4/chatbot/dependency-check/suppressions.xml
  cloudbank-v4/chatbot/pom.xml
  cloudbank-v4/chatbot/src/main/java/com/example/chatbot/controller/ChatController.java
  cloudbank-v4/chatbot/src/main/resources/application.yaml
  cloudbank-v4/chatbot/src/main/resources/banner.txt
  cloudbank-v4/deploy-cmds/delete-cb.txt
  cloudbank-v4/pom.xml
  docs-source/cloudbank/content/deploy-cli/build.md
  docs-source/cloudbank/content/deploy-cli/chatbot.md
  docs-source/cloudbank/content/springai/simple-chat.md
Labels: OCA Verified, cloudbank

#975 Customer bug report. Fix OCI command for sub compartments
  workshops/oracleAQ/setup.sh
Labels: OCA Verified

#963 fixes to free-trial provisioning
  docs-source/cloudbank/content/provision/install-free-trial.md
Labels: documentation, OCA Verified

#977 update docs with missing versions
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/setup/_index.md
Labels: OCA Verified

#978 add ai sandbox docs
  docs-source/spring/content/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/static/ai-microservices-sandbox.png
Labels: OCA Verified

#980 Updates to the TxEventQ Java sample
  code-teq/javaTeq/README.md
  code-teq/javaTeq/pom.xml
  code-teq/javaTeq/src/main/java/com/oracle/example/ConsumeTxEventQ.java
  code-teq/javaTeq/src/main/java/com/oracle/example/CreateTEQ.java
  code-teq/javaTeq/src/main/java/com/oracle/example/CreateTxEventQ.java
  code-teq/javaTeq/src/main/java/com/oracle/example/PublishTEQ.java
  code-teq/javaTeq/src/main/java/com/oracle/example/PublishTxEventQ.java
  code-teq/javaTeq/user_perm.sql
Labels: OCA Verified
