Repository oracle/microservices-datadriven, pull requests merged in 2024-04, with the labels that each got.

#868 kubectl get secret fix for zsh issue
  docs-source/spring/content/infrastructure/databaseaccess/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/soc/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/security/azn-server/_index.md
Labels: OCA Verified

#869 Publish Andy's doc updates
  spring/404.html
  spring/azure/index.html
  spring/blogs/index.html
  spring/development/cli/index.html
  spring/development/envvars/index.html
  spring/development/index.html
  spring/development/project/index.html
  spring/development/setup/index.html
  spring/get-help/index.html
  spring/get-help/troubleshooting/index.html
  spring/getting-started/index.html
  spring/index.html
  spring/infrastructure/database/index.html
  spring/infrastructure/databaseaccess/index.html
  spring/infrastructure/index.html
  spring/infrastructure/kubernetes/index.html
  spring/infrastructure/networking/index.html
  spring/observability/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/on-premises/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/platform/apigw/index.html
  spring/platform/conductor/index.html
  spring/platform/config/index.html
  spring/platform/eureka/index.html
  spring/platform/index.html
  spring/platform/microtx/index.html
  spring/platform/soc/index.html
  spring/platform/spring-admin/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/sampleapp/index.html
  spring/search/en.data.min.json
  spring/security/azn-server/index.html
  spring/security/index.html
  spring/setup/index.html
  spring/starters/aqjms/index.html
  spring/starters/index.html
  spring/starters/ucp/index.html
  spring/starters/wallet/index.html
  spring/tags/index.html
  spring/uninstall/index.html
  spring/upgrade/index.html
Labels: documentation, OCA Verified

#871 Add GraalVM 21 Image
  .github/actions/process-image/action.yml
  .github/workflows/obaas-base-image.yml
Labels: OCA Verified

#872 Directory and dummy application
  tolldemo/HELP.md
  tolldemo/pom.xml
  tolldemo/src/main/java/com/example/tolldemo/TolldemoApplication.java
  tolldemo/src/main/resources/application.properties
  tolldemo/src/test/java/com/example/tolldemo/TolldemoApplicationTests.java
Labels: OCA Verified, toll-demo

#873 Label generator code for tollbooth demo
  tolldemo/TEMP
  tolldemo/label-generator/pom.xml
  tolldemo/label-generator/src/main/java/com/example/labelgenerator/LabelGeneratorApplication.java
  tolldemo/label-generator/src/main/resources/application.properties
  tolldemo/label-generator/src/main/resources/example.jsonl
  tolldemo/label-generator/src/main/resources/input-files.txt
  tolldemo/label-generator/src/test/java/com/example/labelgenerator/LabelGeneratorApplicationTests.java
  tolldemo/tolldemo/pom.xml
  tolldemo/tolldemo/src/main/java/com/example/tolldemo/TolldemoApplication.java
  tolldemo/tolldemo/src/main/resources/application.properties
  tolldemo/tolldemo/src/test/java/com/example/tolldemo/TolldemoApplicationTests.java
Labels: OCA Verified

#876 add new blog posts
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#880 bump kubernetes_version to v1.29.1
  grabdish/terraform/main_var.tf
  infra/k8s/oke/terraform/main_var.tf
Labels: OCA Verified

#870 Custom install update
  docs-source/spring/content/on-premises/_index.md
Labels: OCA Verified

#881 tolldemo: finisihed datagen
  tolldemo/data-generator/src/main/java/com/example/datagenerator/DataGeneratorApplication.java
  tolldemo/data-generator/src/main/java/com/example/datagenerator/State.java
  tolldemo/data-generator/src/main/resources/input-files.txt
Labels: OCA Verified, toll-demo

#875 Init checkin
  tolldemo/toll-reader/.gitignore
  tolldemo/toll-reader/README.md
  tolldemo/toll-reader/aq.sql
  tolldemo/toll-reader/pom.xml
  tolldemo/toll-reader/src/main/java/com/example/tollreader/CarType.java
  tolldemo/toll-reader/src/main/java/com/example/tollreader/State.java
  tolldemo/toll-reader/src/main/java/com/example/tollreader/TollreaderApplication.java
  tolldemo/toll-reader/src/main/resources/application.yaml
  tolldemo/toll-reader/src/test/java/com/example/tollreader/TollreaderApplicationTests.java
Labels: OCA Verified, toll-demo

#883 tolldemo: make sender start and stoppable
  tolldemo/toll-reader/pom.xml
  tolldemo/toll-reader/src/main/java/com/example/tollreader/Controller.java
  tolldemo/toll-reader/src/main/java/com/example/tollreader/MessageTaskExecutor.java
  tolldemo/toll-reader/src/main/java/com/example/tollreader/TollreaderApplication.java
Labels: OCA Verified

#882 Journal app
  tolldemo/journal-app/.gitignore
  tolldemo/journal-app/pom.xml
  tolldemo/journal-app/src/main/java/com/example/journalapp/JournalAppApplication.java
  tolldemo/journal-app/src/main/java/com/example/journalapp/controller/JournalController.java
  tolldemo/journal-app/src/main/java/com/example/journalapp/model/Journal.java
  tolldemo/journal-app/src/main/java/com/example/journalapp/repository/JournalRepository.java
  tolldemo/journal-app/src/main/resources/application.yaml
  tolldemo/journal-app/src/main/resources/schema.sql
  tolldemo/journal-app/src/test/java/com/example/journalapp/JournalAppApplicationTests.java
Labels: OCA Verified, toll-demo
