Repository oracle/microservices-datadriven, pull requests merged in 2024-03, with the labels that each got.

#847 Release Notes
  docs-source/spring/content/release-notes/_index.md
Labels: documentation, OCA Verified

#848 Fix index page
  docs-source/spring/content/_index.md
Labels: documentation, OCA Verified

#849 Remove 1.1.1 references
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/soc/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/setup/_index.md
Labels: documentation, OCA Verified

#850 Documentation updates
  docs-source/spring/content/_index.md
  docs-source/spring/content/infrastructure/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: documentation, OCA Verified

#855 fix db pre-req
  docs-source/spring/content/on-premises/_index.md
Labels: OCA Verified

#858 1.1.3 Docu updates
  docs-source/spring/content/_index.md
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/get-help/_index.md
  docs-source/spring/content/infrastructure/databaseaccess/_index.md
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-admin-connect.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-bastion.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-cloud-portal-details.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-cloud-portal.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-download-wallet.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-private-ip.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-select-db.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-show-tns.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-sqlcl-load-wallet.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-adb-wallet-password.png
  docs-source/spring/content/infrastructure/databaseaccess/oci-bastion-session-create.png
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/metrics/vault-grafana.png
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/platform/eureka/obaas-eureka-dashboard.png
  docs-source/spring/content/platform/soc/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/platform/spring-admin/obaas-springadmin-apps.png
  docs-source/spring/content/platform/spring-admin/obaas-springadmin-svc-details.png
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vault/vault-create-secret.png
  docs-source/spring/content/platform/vault/vault-grafana.png
  docs-source/spring/content/platform/vault/vault-home.png
  docs-source/spring/content/platform/vault/vault-kv-v2-home.png
  docs-source/spring/content/platform/vault/vault-login.png
  docs-source/spring/content/platform/vault/vault-secret.png
  docs-source/spring/content/platform/vault/vault-show-secret.png
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/sampleapp/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/security/azn-server/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/ebaas-mp-listing.png
  docs-source/spring/content/setup/oci-stack-app-name.png
  docs-source/spring/data/menu/main.yaml
Labels: documentation, OCA Verified

#860 Fix prometheus problem
  cloudbank-v32/apisix-routes/create-accounts-route.sh
  cloudbank-v32/apisix-routes/create-creditscore-route.sh
  cloudbank-v32/apisix-routes/create-customer-route.sh
  cloudbank-v32/apisix-routes/create-customer32-route.sh
  cloudbank-v32/apisix-routes/create-testrunner-route.sh
  cloudbank-v32/apisix-routes/create-transfer-route.sh
Labels: OCA Verified

#864 publish link fixes
  spring/404.html
  spring/azure/index.html
  spring/blogs/index.html
  spring/development/cli/index.html
  spring/development/envvars/index.html
  spring/development/index.html
  spring/development/project/index.html
  spring/development/setup/index.html
  spring/get-help/index.html
  spring/get-help/troubleshooting/index.html
  spring/getting-started/index.html
  spring/index.html
  spring/infrastructure/database/index.html
  spring/infrastructure/databaseaccess/index.html
  spring/infrastructure/index.html
  spring/infrastructure/kubernetes/index.html
  spring/infrastructure/networking/index.html
  spring/observability/index.html
  spring/observability/metrics/index.html
  spring/observability/tracing/index.html
  spring/on-premises/index.html
  spring/on-premises/macos_ventura/index.html
  spring/on-premises/ol8/index.html
  spring/platform/apigw/index.html
  spring/platform/conductor/index.html
  spring/platform/config/index.html
  spring/platform/eureka/index.html
  spring/platform/index.html
  spring/platform/microtx/index.html
  spring/platform/soc/index.html
  spring/platform/spring-admin/index.html
  spring/platform/vault/index.html
  spring/platform/vscode-plugin/index.html
  spring/release-notes/index.html
  spring/sampleapp/index.html
  spring/security/azn-server/index.html
  spring/security/index.html
  spring/setup/index.html
  spring/starters/aqjms/index.html
  spring/starters/index.html
  spring/starters/ucp/index.html
  spring/starters/wallet/index.html
  spring/tags/index.html
  spring/uninstall/index.html
  spring/upgrade/index.html
Labels: documentation, OCA Verified

#861 Cloudbank version & properties
  cloudbank-v32/README.md
  cloudbank-v32/account/pom.xml
  cloudbank-v32/account/src/main/java/com/example/accounts/model/Account.java
  cloudbank-v32/account/src/main/resources/application.yaml
  cloudbank-v32/account/src/main/resources/db/changelog/data.sql
  cloudbank-v32/account/src/main/resources/db/changelog/table.sql
  cloudbank-v32/account/src/main/resources/db/changelog/txeventq.sql
  cloudbank-v32/apisix-routes/create-accounts-route.sh
  cloudbank-v32/apisix-routes/create-creditscore-route.sh
  cloudbank-v32/apisix-routes/create-customer-route.sh
  cloudbank-v32/apisix-routes/create-customer32-route.sh
  cloudbank-v32/apisix-routes/create-testrunner-route.sh
  cloudbank-v32/apisix-routes/create-transfer-route.sh
  cloudbank-v32/checks/pom.xml
  cloudbank-v32/checks/src/main/resources/application.yaml
  cloudbank-v32/creditscore/src/main/resources/application.yaml
  cloudbank-v32/customer/src/main/resources/application.yaml
  cloudbank-v32/customer/src/main/resources/db/changelog/data.sql
  cloudbank-v32/customer/src/main/resources/db/changelog/table.sql
  cloudbank-v32/customer32/pom.xml
  cloudbank-v32/customer32/src/main/resources/application.yaml
  cloudbank-v32/customer32/src/main/resources/db/changelog/data.sql
  cloudbank-v32/customer32/src/main/resources/db/changelog/table.sql
  cloudbank-v32/pom.xml
  cloudbank-v32/testrunner/pom.xml
  cloudbank-v32/testrunner/src/main/resources/application.yaml
  cloudbank-v32/transfer/pom.xml
  cloudbank-v32/transfer/src/main/resources/application.yaml
Labels: OCA Verified, cloudbank
