Repository oracle/microservices-datadriven, pull requests merged in 2024-09, with the labels that each got.

#930 Fix README
  cloudbank-v4/README.md
Labels: bug, documentation, OCA Verified

#931 Update README and CB updates
  cloudbank-v4/README.md
  cloudbank-v4/account/src/main/java/com/example/accounts/controller/AccountController.java
  cloudbank-v4/customer/src/main/java/com/example/customer/controller/CustomerController.java
  docs-source/cloudbank/content/account/cr-accounts.md
  docs-source/cloudbank/content/account/deploy.md
  docs-source/cloudbank/content/check/check-processing.md
  docs-source/cloudbank/content/check/create-testrunner.md
  docs-source/cloudbank/content/check/update-account.md
  docs-source/cloudbank/content/deploy-cli/deploy.md
  docs-source/cloudbank/content/devenv/oractl.md
  docs-source/cloudbank/content/saga/deploy.md
  docs-source/cloudbank/content/saga/deposit.md
Labels: OCA Verified, cloudbank

#932 relnotes and version upgrade
  docs-source/spring/content/_index.md
  docs-source/spring/content/release-notes/_index.md
Labels: documentation, OCA Verified

#928 Add Blogs
  docs-source/spring/content/blogs/_index.md
Labels: OCA Verified

#933 Intellij plugin
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/intellij-plugin/_index.md
  docs-source/spring/content/platform/intellij-plugin/images/add-namespace.png
  docs-source/spring/content/platform/intellij-plugin/images/create-autoscaler.png
  docs-source/spring/content/platform/intellij-plugin/images/create-prop.png
  docs-source/spring/content/platform/intellij-plugin/images/explore-resources.png
  docs-source/spring/content/platform/intellij-plugin/images/grafana-connect.png
  docs-source/spring/content/platform/intellij-plugin/images/install-from-disk.png
  docs-source/spring/content/platform/intellij-plugin/images/namespace-created.png
  docs-source/spring/content/platform/intellij-plugin/images/open-settings.png
  docs-source/spring/content/platform/intellij-plugin/images/platform-services.png
  docs-source/spring/content/platform/intellij-plugin/images/prop-created.png
  docs-source/spring/content/platform/intellij-plugin/images/publish-workload.png
  docs-source/spring/content/platform/intellij-plugin/images/settings.png
  docs-source/spring/content/platform/intellij-plugin/images/test-connection.png
  docs-source/spring/content/platform/intellij-plugin/images/upload-jar.png
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#936 IntelliJ Plugin: faq/issues
  docs-source/spring/content/platform/intellij-plugin/_index.md
Labels: OCA Verified

#935 GPU docs for 1.3.0 and simple chatbot module for Cloudbank
  cloudbank-v4/chatbot/pom.xml
  cloudbank-v4/chatbot/src/main/java/com/example/chatbot/ChatbotApplication.java
  cloudbank-v4/chatbot/src/main/java/com/example/chatbot/controller/ChatController.java
  cloudbank-v4/chatbot/src/main/resources/application.yaml
  docs-source/cloudbank/content/_index.md
  docs-source/cloudbank/content/springai/_index.md
  docs-source/cloudbank/content/springai/simple-chat.md
  docs-source/cloudbank/hugo.toml
  docs-source/cloudbank/static/images/favicon.png
  docs-source/spring/content/infrastructure/gpu/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#938 minor updates to cb diagram and description
  docs-source/cloudbank/content/_index.md
  docs-source/spring/content/_index.md
  docs-source/spring/static/cloudbank-hol.png
Labels: OCA Verified

#940 oops its case sensitive
  docs-source/spring/content/_index.md
Labels: OCA Verified

#942 fix typo
  spring/index.html
Labels: OCA Verified

#934 Refactor documentation
  data-refactoring-advisor/hands-on-lab/README.md
  data-refactoring-advisor/hands-on-lab/collect-database-workload/README.md
  data-refactoring-advisor/hands-on-lab/community-detection/README.md
  data-refactoring-advisor/hands-on-lab/create-graph-tables/README.md
  data-refactoring-advisor/hands-on-lab/create-graph/README.md
  data-refactoring-advisor/hands-on-lab/images/OrderCatalog.png
  data-refactoring-advisor/hands-on-lab/images/PersonPrsnl.png
  data-refactoring-advisor/hands-on-lab/images/PharmacyManagement.png
  data-refactoring-advisor/hands-on-lab/images/clickCreateGraph.png
  data-refactoring-advisor/hands-on-lab/images/comm0.png
  data-refactoring-advisor/hands-on-lab/images/comm3.png
  data-refactoring-advisor/hands-on-lab/images/commNodes.png
  data-refactoring-advisor/hands-on-lab/images/createGraph.png
  data-refactoring-advisor/hands-on-lab/images/createNotebook.png
  data-refactoring-advisor/hands-on-lab/images/dbactions.png
  data-refactoring-advisor/hands-on-lab/images/defineGraph.png
  data-refactoring-advisor/hands-on-lab/images/edgesCorrect.png
  data-refactoring-advisor/hands-on-lab/images/finalWeightedGraph.png
  data-refactoring-advisor/hands-on-lab/images/findCommID.png
  data-refactoring-advisor/hands-on-lab/images/goodGraph.png
  data-refactoring-advisor/hands-on-lab/images/graphComplete.png
  data-refactoring-advisor/hands-on-lab/images/graphSuccess.png
  data-refactoring-advisor/hands-on-lab/images/graphstudio.png
  data-refactoring-advisor/hands-on-lab/images/incoming.png
  data-refactoring-advisor/hands-on-lab/images/infoMap.png
  data-refactoring-advisor/hands-on-lab/images/listGraphsLoaded.png
  data-refactoring-advisor/hands-on-lab/images/listNodes.png
  data-refactoring-advisor/hands-on-lab/images/loadGraph.png
  data-refactoring-advisor/hands-on-lab/images/newHighlight.png
  data-refactoring-advisor/hands-on-lab/images/newNotebookInfo.png
  data-refactoring-advisor/hands-on-lab/images/notebookGraphLoad.png
  data-refactoring-advisor/hands-on-lab/images/numCommunities.png
  data-refactoring-advisor/hands-on-lab/images/outgoing.png
  data-refactoring-advisor/hands-on-lab/images/pgx.png
  data-refactoring-advisor/hands-on-lab/images/qscreatetables.png
  data-refactoring-advisor/hands-on-lab/images/qsimport.png
  data-refactoring-advisor/hands-on-lab/images/qsimportsuccess.png
  data-refactoring-advisor/hands-on-lab/images/renderedGraph.png
  data-refactoring-advisor/hands-on-lab/images/runIt.png
  data-refactoring-advisor/hands-on-lab/images/selectEdgesandNodes.png
  data-refactoring-advisor/hands-on-lab/images/selectpgql.png
  data-refactoring-advisor/hands-on-lab/images/setEdgeWeight.png
  data-refactoring-advisor/hands-on-lab/images/swapEdges.png
  data-refactoring-advisor/hands-on-lab/images/vertex1.png
  data-refactoring-advisor/hands-on-lab/images/vertex2.png
  data-refactoring-advisor/hands-on-lab/images/vertexProperty.png
  data-refactoring-advisor/hands-on-lab/images/weightedPagerank.png
  data-refactoring-advisor/hands-on-lab/import-data/MED_RECS_IMPORT_EDGES.csv
  data-refactoring-advisor/hands-on-lab/import-data/MED_RECS_IMPORT_NODES.csv
  data-refactoring-advisor/hands-on-lab/import-data/edges.csv
  data-refactoring-advisor/hands-on-lab/import-data/nodes.csv
  data-refactoring-advisor/hands-on-lab/medical-data/README.md
  data-refactoring-advisor/hands-on-lab/pgql/README.md
  data-refactoring-advisor/hands-on-lab/quickstart/README.md
Labels: OCA Verified

#943 Add SpringBoot link example
  data-refactoring-advisor/hands-on-lab/README.md
Labels: OCA Verified

#944 Setup documentation
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/setup/ebaas-mp-listing.png
  docs-source/spring/content/setup/ebaas-stack-page1.png
  docs-source/spring/content/setup/oci-private-template-create-stack-config-review.png
  docs-source/spring/content/setup/oci-stack-oke-options.png
  docs-source/spring/content/setup/oci-stack-passwords.png
Labels: documentation, OCA Verified

#948 update soc access and port forwarding instructions for free-tier install
  docs-source/cloudbank/content/provision/images/add-ingress-rule.png
  docs-source/cloudbank/content/provision/install-free-trial.md
Labels: OCA Verified

#953 Remove UKOUG
  ukoug/load_gen/customer.js
  ukoug/load_gen/customer.sh
  ukoug/pom.xml
  ukoug/src/main/java/com/example/customer/CustomerApplication.java
  ukoug/src/main/java/com/example/customer/controller/CustomerController.java
  ukoug/src/main/java/com/example/customer/model/Customers.java
  ukoug/src/main/java/com/example/customer/repository/CustomersRepository.java
  ukoug/src/main/resources/application.yaml
  ukoug/src/main/resources/banner.txt
  ukoug/src/main/resources/data.sql
Labels: OCA Verified

#955 naming update
  docs-source/spring/config.toml
  docs-source/spring/content/_index.md
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/development/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/development/envvars.md
  docs-source/spring/content/development/project.md
  docs-source/spring/content/development/setup.md
  docs-source/spring/content/get-help/_index.md
  docs-source/spring/content/get-help/troubleshooting/_index.md
  docs-source/spring/content/getting-started/_index.md
  docs-source/spring/content/infrastructure/_index.md
  docs-source/spring/content/infrastructure/database/_index.md
  docs-source/spring/content/infrastructure/databaseaccess/_index.md
  docs-source/spring/content/infrastructure/gpu/_index.md
  docs-source/spring/content/infrastructure/kubernetes/_index.md
  docs-source/spring/content/infrastructure/networking/_index.md
  docs-source/spring/content/observability/_index.md
  docs-source/spring/content/observability/metrics/_index.md
  docs-source/spring/content/observability/tracing/_index.md
  docs-source/spring/content/on-premises/_index.md
  docs-source/spring/content/on-premises/macos_ventura/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/_index.md
  docs-source/spring/content/platform/apigw/_index.md
  docs-source/spring/content/platform/conductor/_index.md
  docs-source/spring/content/platform/config/_index.md
  docs-source/spring/content/platform/eureka/_index.md
  docs-source/spring/content/platform/intellij-plugin/_index.md
  docs-source/spring/content/platform/microtx/_index.md
  docs-source/spring/content/platform/soc/_index.md
  docs-source/spring/content/platform/spring-admin/_index.md
  docs-source/spring/content/platform/vault/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/sampleapp/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/content/security/azn-server/_index.md
  docs-source/spring/content/setup/_index.md
  docs-source/spring/content/uninstall/_index.md
  docs-source/spring/content/upgrade/_index.md
Labels: OCA Verified

#956 Naming and version updates
  cloudbank-v4/pom.xml
  docs-source/cloudbank/content/_index.md
  docs-source/cloudbank/content/account/_index.md
  docs-source/cloudbank/content/account/create-project.md
  docs-source/cloudbank/content/account/deploy.md
  docs-source/cloudbank/content/account/expose.md
  docs-source/cloudbank/content/account/images/obaas-spring-init-2.png
  docs-source/cloudbank/content/account/intro.md
  docs-source/cloudbank/content/backend/admin.md
  docs-source/cloudbank/content/backend/apisix.md
  docs-source/cloudbank/content/backend/database.md
  docs-source/cloudbank/content/backend/intro.md
  docs-source/cloudbank/content/backend/k8s.md
  docs-source/cloudbank/content/check/check-processing.md
  docs-source/cloudbank/content/check/create-testrunner.md
  docs-source/cloudbank/content/check/images/spring-boot-version.png
  docs-source/cloudbank/content/check/update-account.md
  docs-source/cloudbank/content/cleanup/_index.md
  docs-source/cloudbank/content/cleanup/intro.md
  docs-source/cloudbank/content/cleanup/uninstall-mp.md
  docs-source/cloudbank/content/deploy-cli/_index.md
  docs-source/cloudbank/content/deploy-cli/deploy.md
  docs-source/cloudbank/content/deploy-cli/intro.md
  docs-source/cloudbank/content/deploy-ide/_index.md
  docs-source/cloudbank/content/deploy-ide/intro.md
  docs-source/cloudbank/content/deploy-ide/using-vscode.md
  docs-source/cloudbank/content/devenv/db-access.md
  docs-source/cloudbank/content/devenv/ide-plugin.md
  docs-source/cloudbank/content/devenv/intro.md
  docs-source/cloudbank/content/devenv/jdk.md
  docs-source/cloudbank/content/devenv/oractl.md
  docs-source/cloudbank/content/provision/_index.md
  docs-source/cloudbank/content/provision/install-free-trial.md
  docs-source/cloudbank/content/provision/install-local.md
  docs-source/cloudbank/content/provision/install-mp.md
  docs-source/cloudbank/content/provision/intro.md
  docs-source/cloudbank/content/saga/deploy.md
  docs-source/cloudbank/content/saga/images/spring-boot-version.png
  docs-source/cloudbank/content/saga/learn-lra.md
  docs-source/cloudbank/content/saga/prepare.md
  docs-source/cloudbank/content/saga/transfer-service.md
  docs-source/cloudbank/content/springai/simple-chat.md
Labels: OCA Verified

#958 Renaming
  README.md
  cloudbank-v4/README.md
  cloudbank-v4/customer32/README.md
  cloudbank-v4/local-environment/obaas.sh
  cloudbank-v4/pom.xml
  docs-source/cloudbank/content/account/intro.md
  docs-source/spring/content/_index.md
  docs-source/spring/content/azure/_index.md
  docs-source/spring/content/blogs/_index.md
  docs-source/spring/content/development/_index.md
  docs-source/spring/content/development/cli/_index.md
  docs-source/spring/content/infrastructure/databaseaccess/_index.md
  docs-source/spring/content/on-premises/ol8/_index.md
  docs-source/spring/content/platform/vscode-plugin/_index.md
  docs-source/spring/content/setup/_index.md
Labels: OCA Verified

#960 Updates to README
  cloudbank-v4/README.md
  cloudbank-v4/images/admin_server.png
  cloudbank-v4/images/grafana_login.png
  cloudbank-v4/images/prom_data.png
  cloudbank-v4/images/prometheus.png
  cloudbank-v4/images/serviceops_dashboard.png
  cloudbank-v4/images/serviceops_login.png
  cloudbank-v4/images/vault_dashboard.png
  cloudbank-v4/images/vault_login.png
Labels: documentation, OCA Verified, cloudbank

#962 Soc naming updates
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/soc/_index.md
  docs-source/spring/content/platform/soc/soc-alerts.png
  docs-source/spring/content/platform/soc/soc-create-ns.png
  docs-source/spring/content/platform/soc/soc-create-workload-bind.png
  docs-source/spring/content/platform/soc/soc-create-workload-db.png
  docs-source/spring/content/platform/soc/soc-create-workload-details.png
  docs-source/spring/content/platform/soc/soc-create-workload-progress.png
  docs-source/spring/content/platform/soc/soc-create-workload-route.png
  docs-source/spring/content/platform/soc/soc-create-workload-upload.png
  docs-source/spring/content/platform/soc/soc-dashboard.png
  docs-source/spring/content/platform/soc/soc-delete-ns.png
  docs-source/spring/content/platform/soc/soc-delete-user.png
  docs-source/spring/content/platform/soc/soc-delete-workload.png
  docs-source/spring/content/platform/soc/soc-diag-data.png
  docs-source/spring/content/platform/soc/soc-forgot-passwd.png
  docs-source/spring/content/platform/soc/soc-forgot-username.png
  docs-source/spring/content/platform/soc/soc-heartbeat.png
  docs-source/spring/content/platform/soc/soc-login-page.png
  docs-source/spring/content/platform/soc/soc-manage-identity-chg-email.png
  docs-source/spring/content/platform/soc/soc-manage-identity-chg-psswd.png
  docs-source/spring/content/platform/soc/soc-manage-identity-chg-role.png
  docs-source/spring/content/platform/soc/soc-manage-identity-create-user.png
  docs-source/spring/content/platform/soc/soc-manage-identity.png
  docs-source/spring/content/platform/soc/soc-manage-namespaces.png
  docs-source/spring/content/platform/soc/soc-manage-workloads.png
  docs-source/spring/content/platform/soc/soc-reset-psswd-otp.png
  docs-source/spring/content/platform/soc/soc-reset-psswd.png
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/content/security/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified
