Repository oracle/microservices-datadriven, pull requests merged in 2024-08, with the labels that each got.

#918 Added BYO vnc info #797
  docs-source/spring/content/infrastructure/database/_index.md
  docs-source/spring/content/infrastructure/database/images/byo-vcn.png
Labels: documentation, OCA Verified

#920 Version upgrades of Cloudbank32
  cloudbank-v32/account/pom.xml
  cloudbank-v32/checks/pom.xml
  cloudbank-v32/creditscore/pom.xml
  cloudbank-v32/customer/pom.xml
  cloudbank-v32/pom.xml
  cloudbank-v32/testrunner/pom.xml
  cloudbank-v32/transfer/pom.xml
Labels: OCA Verified

#923 change to 23ai
  workshops/oracleAQ/setup.sh
Labels: bug, OCA Verified

#892 Tolldemo cleanup
  tolldemo/TEMP
  tolldemo/journal-app/src/main/resources/schema.sql
  tolldemo/queue-reader/README.md
  tolldemo/setup.sql
  tolldemo/toll-reader/aq.sql
  tolldemo/toll-reader/create-tables.sql
Labels: OCA Verified, toll-demo

#926 more updates for cloudbank v4
  cloudbank-v4/README.md
  cloudbank-v4/pom.xml
  docs-source/cloudbank/content/cleanup/uninstall-local.md
  docs-source/cloudbank/content/cleanup/uninstall-mp.md
  docs-source/cloudbank/content/provision/images/obaas-parse-application.png
  docs-source/cloudbank/content/provision/images/obaas-parse-dashboard.png
  docs-source/cloudbank/content/provision/images/obaas-stack-with-parse.png
  docs-source/cloudbank/content/provision/install-free-trial.md
  docs-source/cloudbank/content/provision/install-local.md
  docs-source/cloudbank/content/provision/install-mp.md
  docs-source/cloudbank/content/provision/intro.md
  docs-source/cloudbank/content/springai/_index.md
Labels: OCA Verified
