Repository oracle/microservices-datadriven, pull requests merged in 2025-03, with the labels that each got.

#1044 TxEventQ docs update
  docs-source/transactional-event-queues/content/getting-started/advanced-features.md
  docs-source/transactional-event-queues/content/getting-started/core-concepts.md
  docs-source/transactional-event-queues/content/getting-started/message-operations.md
  docs-source/transactional-event-queues/content/getting-started/queue-management.md
Labels: OCA Verified

#1045 Update TxEventQ Docs
  transactional-event-queues/404.html
  transactional-event-queues/aq-migration/index.html
  transactional-event-queues/aq-migration/migration/index.html
  transactional-event-queues/categories/index.html
  transactional-event-queues/getting-started/advanced-features/index.html
  transactional-event-queues/getting-started/core-concepts/index.html
  transactional-event-queues/getting-started/index.html
  transactional-event-queues/getting-started/index.xml
  transactional-event-queues/getting-started/message-operations/index.html
  transactional-event-queues/getting-started/queue-management/index.html
  transactional-event-queues/index.html
  transactional-event-queues/kafka/concepts/index.html
  transactional-event-queues/kafka/developing-with-kafka/index.html
  transactional-event-queues/kafka/index.html
  transactional-event-queues/kafka/kafka-connectors/index.html
  transactional-event-queues/kafka/transactional-messaging/index.html
  transactional-event-queues/more/credits/index.html
  transactional-event-queues/observability/exporter/index.html
  transactional-event-queues/observability/index.html
  transactional-event-queues/observability/tuning/index.html
  transactional-event-queues/observability/views/index.html
  transactional-event-queues/search/index.html
  transactional-event-queues/searchindex.en.js
  transactional-event-queues/spring-boot/index.html
  transactional-event-queues/spring-boot/jms/index.html
  transactional-event-queues/spring-boot/kafka/index.html
  transactional-event-queues/spring-boot/stream-binder/index.html
  transactional-event-queues/tags/index.html
Labels: OCA Verified

#1046 Add doc around imagedeletebyworkload & lint
  docs-source/spring/content/development/cli/_index.md
Labels: documentation, OCA Verified

#1047 New name and CB4 update
  cloudbank-v4/deploy-cmds/deploy-cbv4-v2api-openjdk.txt
  cloudbank-v4/deploy-cmds/undeploy-cbv4-v2.txt
  cloudbank-v4/pom.xml
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/aiexpforapps/_index.md
  docs-source/spring/content/platform/aiexpforapps/ai-microservices-sandbox.png
  docs-source/spring/content/release-notes/_index.md
  docs-source/spring/data/menu/main.yaml
Labels: OCA Verified

#1048 Change clone command
  docs-source/cloudbank/content/deploy-cli/get-code.md
  docs-source/cloudbank/content/provision/install-local.md
Labels: documentation, OCA Verified, cloudbank

#1050 Fix image build errors
  .github/actions/process-image/action-base.yml
  .github/actions/process-image/action-openjdk.yml
  .github/workflows/obaas-base-image.yml
  .github/workflows/openjdk-base-image.yml
Labels: bug, OCA Verified

#1052 Fixed image build typo
  .github/workflows/openjdk-base-image.yml
Labels: OCA Verified

#1053 CB fixes and doc updates
  cloudbank-v4/chatbot/pom.xml
  cloudbank-v4/pom.xml
Labels: OCA Verified, cloudbank
