Repository oracle/microservices-datadriven, pull requests merged in 2025-02, with the labels that each got.

#1040 Upgrade SB and SCO
  cloudbank-v4/pom.xml
Labels: OCA Verified, cloudbank

#1042 Update action.yml
  .github/actions/process-image/action.yml
Labels: OCA Verified

#1041 observability changes to application configs
  cloudbank-v4/account/pom.xml
  cloudbank-v4/account/src/main/java/com/example/accounts/AccountsApplication.java
  cloudbank-v4/account/src/main/java/com/example/accounts/controller/AccountController.java
  cloudbank-v4/account/src/main/resources/application.yaml
  cloudbank-v4/chatbot/pom.xml
  cloudbank-v4/chatbot/src/main/java/com/example/chatbot/ChatbotApplication.java
  cloudbank-v4/chatbot/src/main/resources/application.yaml
  cloudbank-v4/checks/pom.xml
  cloudbank-v4/checks/src/main/java/com/example/checks/ChecksApplication.java
  cloudbank-v4/checks/src/main/resources/application.yaml
  cloudbank-v4/common/checkstyle/checkstyle.xml
  cloudbank-v4/common/checkstyle/suppressions.xml
  cloudbank-v4/common/dependency-check/suppressions.xml
  cloudbank-v4/common/pom.xml
  cloudbank-v4/common/src/main/java/com/example/common/filter/LoggingFilterConfig.java
  cloudbank-v4/common/src/main/resources/common.yaml
  cloudbank-v4/creditscore/pom.xml
  cloudbank-v4/creditscore/src/main/java/com/example/creditscore/CreditscoreApplication.java
  cloudbank-v4/creditscore/src/main/resources/application.yaml
  cloudbank-v4/customer/pom.xml
  cloudbank-v4/customer/src/main/java/com/example/customer/CustomerApplication.java
  cloudbank-v4/customer/src/main/resources/application.yaml
  cloudbank-v4/customer32/pom.xml
  cloudbank-v4/customer32/src/main/resources/application.yaml
  cloudbank-v4/pom.xml
  cloudbank-v4/testrunner/pom.xml
  cloudbank-v4/testrunner/src/main/java/com/example/testrunner/TestrunnerApplication.java
  cloudbank-v4/testrunner/src/main/resources/application.yaml
  cloudbank-v4/transfer/pom.xml
  cloudbank-v4/transfer/src/main/java/com/example/transfer/TransferApplication.java
  cloudbank-v4/transfer/src/main/resources/application.yaml
Labels: OCA Verified

#1037 Moved AI Sandbox to it's own menu item
  docs-source/spring/content/_index.md
  docs-source/spring/content/platform/aisandbox/_index.md
  docs-source/spring/content/platform/aisandbox/ai-microservices-sandbox.png
  docs-source/spring/data/menu/main.yaml
  docs-source/spring/themes/hugo-geekdoc/i18n/en.yaml
Labels: documentation, OCA Verified

#1038 Cleaned up the Spring Starter page
  docs-source/spring/content/starters/_index.md
  docs-source/spring/content/starters/aqjms.md
  docs-source/spring/content/starters/ucp.md
  docs-source/spring/content/starters/wallet.md
  docs-source/spring/data/menu/main.yaml
Labels: documentation, OCA Verified

#1043 Update Doc for new API
  data-refactoring-advisor/hands-on-lab/community-detection/README.md
  data-refactoring-advisor/hands-on-lab/images/listGraphsLoaded.png
Labels: OCA Verified
